FROM node:22-alpine

WORKDIR /app

# Add dependencies for development and OpenSSL
RUN apk add --no-cache \
    libc6-compat \
    python3 \
    make \
    g++ \
    openssl \
    openssl-dev

# Copy prisma schema
COPY prisma ./prisma/

# Install dependencies
COPY package*.json ./

RUN npm install

# Generate Prisma client
RUN npx prisma generate

# Copy the rest of the application
COPY . .

# Expose port 3000
EXPOSE 3000

# Start the development server
CMD ["npm", "run", "dev"]
