version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://urlshortener:development@postgres:5432/urlshortener
      - REDIS_URL=redis://redis:6379
      - AUTH_SECRET=2zlB6jZdPPjsyT8z7p+ugNmgNIvT4iMGdgbY+uIP04A=
      - AUTH_URL=http://localhost:3000
      - EMAIL_SERVER_HOST=mailhog
      - EMAIL_SERVER_PORT=1025
      - EMAIL_SERVER_USER=
      - EMAIL_SERVER_PASSWORD=
      - EMAIL_FROM=noreply@sachinmour.com
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - postgres
      - redis
      - mailhog
    command: sh -c "chmod +x ./scripts/wait-for-db.sh && ./scripts/wait-for-db.sh npm run dev"

  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: development
      POSTGRES_DB: urlshortener
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI

volumes:
  postgres_data:
  redis_data:
